name: build and deploy

on: 
  push:
    branches:
    - master

jobs: 
  build-deploy:
    runs - on: ubuntu-latest
    steps:
    -uses: actions/checkout@v2


  #缓存依赖
  - name: Cache dependencies
    uses: actions/cache@v1
    with:
      path: ~/.npm
      key: ${{ runner.os }}-node-${{hashFiles('**/package-lock.json')}}
      restore-keys: 
        ${{ runner.os }}-node-
  #安装依赖
  - run: nmp ci
  #打包构建
  - run:  npm run build

  #发布到githubpage
  - name: Deploy
    uses: peaceiris/actions-gh-pages@v2
    env:
      PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      PUBLISH_BRANCH: gh-pages
      PUBLISH_DIR: ./public
